import Head from "next/head"

import NotifyMe from "../components/NotifyMe"

export default function Home() {
  return (
    <div className="h-full ">
      <Head>
        <title>NextJS and Tailwind Template</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col items-center justify-center h-full gap-5 text-center md:gap-10 ">
        <h1 className="text-2xl font-light md:text-5xl text-gray">
          We are launching
          <span className="font-semibold text-black"> soon!</span>
        </h1>
        <p className="text-xl font-light text-veryDarkBlue">
          Subscribe and get notified
        </p>

        <NotifyMe />
        {/* <div className="relative h-[20rem] w-[40rem] flex justify-center items-center">
          <Image src={dashboard} alt="" layout="fill" objectFit="contain" />
        </div> */}
        <img
          src="/illustration-dashboard.png"
          alt=""
          className="w-auto h-auto max-h-96"
        />
      </main>
    </div>
  )
}
